# Generated by Django 4.1.7 on 2023-02-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('superficie', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('credito', models.BooleanField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='obra_images')),
            ],
        ),
    ]
