# Generated by Django 4.1.7 on 2023-02-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='superficie',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='obra',
            old_name='credito',
            new_name='credit',
        ),
        migrations.RenameField(
            model_name='obra',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='obra',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='obra',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='obra',
            old_name='precio',
            new_name='price',
        ),
    ]
